### ISSUE TITLE
Update version in download URL

### ISSUE THREAD

**Issue by nir-krakauer** [apjanke/octave-jsonstuff#16]
The URL needs to be updated under README.md > Installation and usage > Quick start

**Comment by apjanke** [comment]
URL updated: https://github.com/apjanke/octave-jsonstuff/commit/7b54c9e751f4c3ba66d4105acba7b8cbf05470db.

Works for me locally. Look good to you?

Note to self: Next time, follow the darn [Release Checklist](https://github.com/apjanke/octave-jsonstuff/blob/7b54c9e751f4c3ba66d4105acba7b8cbf05470db/doc-project/Developer-Notes.md#release-checklist), which includes an item for updating this URL.

**Comment by nir-krakauer** [comment]
Yes. 0.3.2 works well for me with Octave 6.0 on Linux

**Comment by apjanke** [comment]
Great. Thanks for the report!
