### ISSUE TITLE
jsondecode should return column vector for Matlab compatibility

### ISSUE THREAD

**Issue by mtmiller** [apjanke/octave-jsonstuff#5]
Just trying some simple examples, I noticed that jsondecode returns row vectors, but should be column vectors for compatibility.

Examples

    jsondecode ('[1, 2, 3, 4]')

should return a 4×1 numeric column vector,

    jsondecode ('[{"a": 1}, {"a": 2}]')

should return a 2×1 struct array,

    jsondecode ('["foo", "bar"]')

should return a 2×1 cell string array.

**Comment by apjanke** [comment]
Thanks for catching this!
